"""empty message

Revision ID: 02547ddc8dc0
Revises: 22fea9ae2fbb
Create Date: 2021-03-17 22:28:35.658161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02547ddc8dc0'
down_revision = '22fea9ae2fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
