"""empty message

Revision ID: 07357bab571b
Revises: e5d8a3338910
Create Date: 2024-04-04 16:44:37.843720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07357bab571b'
down_revision = 'e5d8a3338910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('show', sa.Boolean(), nullable=True))
        batch_op.drop_column('location_address')
        batch_op.drop_column('show_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_location', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('show')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
