"""empty message

Revision ID: 1376f17e9d53
Revises: 9a8f7c92490b
Create Date: 2021-07-17 18:43:25.930124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1376f17e9d53'
down_revision = '9a8f7c92490b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convo', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('creation_datetime', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_message_creation_datetime'), 'message', ['creation_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_creation_datetime'), table_name='message')
    op.drop_column('message', 'text')
    op.drop_column('message', 'creation_datetime')
    op.drop_column('convo', 'activated')
    # ### end Alembic commands ###
