"""Tables

Revision ID: 1b5d4cf2bdda
Revises: 
Create Date: 2020-07-16 17:10:53.910828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5d4cf2bdda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('AL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('AR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('AZ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('CA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('CO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('CT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('DC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('DE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('FL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('GA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('HI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('IA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('IL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('IN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('KS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('KY',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('LA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ME',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('MT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ND',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NH',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NJ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('NY',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('OH',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('OK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('OR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('PA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('RI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('SC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('SD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('TN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('TX',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('UT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('VA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('VT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('WA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('WI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('WV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('WY',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('sin_r_lat', sa.Float(), nullable=True),
    sa.Column('cos_r_lat', sa.Float(), nullable=True),
    sa.Column('r_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WY')
    op.drop_table('WV')
    op.drop_table('WI')
    op.drop_table('WA')
    op.drop_table('VT')
    op.drop_table('VA')
    op.drop_table('UT')
    op.drop_table('TX')
    op.drop_table('TN')
    op.drop_table('SD')
    op.drop_table('SC')
    op.drop_table('RI')
    op.drop_table('PA')
    op.drop_table('OR')
    op.drop_table('OK')
    op.drop_table('OH')
    op.drop_table('NY')
    op.drop_table('NV')
    op.drop_table('NM')
    op.drop_table('NJ')
    op.drop_table('NH')
    op.drop_table('NE')
    op.drop_table('ND')
    op.drop_table('NC')
    op.drop_table('MT')
    op.drop_table('MS')
    op.drop_table('MO')
    op.drop_table('MN')
    op.drop_table('MI')
    op.drop_table('ME')
    op.drop_table('MD')
    op.drop_table('MA')
    op.drop_table('LA')
    op.drop_table('KY')
    op.drop_table('KS')
    op.drop_table('IN')
    op.drop_table('IL')
    op.drop_table('ID')
    op.drop_table('IA')
    op.drop_table('HI')
    op.drop_table('GA')
    op.drop_table('FL')
    op.drop_table('DE')
    op.drop_table('DC')
    op.drop_table('CT')
    op.drop_table('CO')
    op.drop_table('CA')
    op.drop_table('AZ')
    op.drop_table('AR')
    op.drop_table('AL')
    op.drop_table('AK')
    # ### end Alembic commands ###
