"""empty message

Revision ID: 1b866f353347
Revises: ad3ea1ed4166
Create Date: 2021-04-27 18:01:12.120566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b866f353347'
down_revision = 'ad3ea1ed4166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_to_user_request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club_to_user_request', 'notification', ['notification_id'], ['id'])
    op.add_column('project_to_user_request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_to_user_request', 'notification', ['notification_id'], ['id'])
    op.add_column('user_to_club_request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_to_club_request', 'notification', ['notification_id'], ['id'])
    op.add_column('user_to_project_request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_to_project_request', 'notification', ['notification_id'], ['id'])
    op.add_column('user_to_user_request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_to_user_request', 'notification', ['notification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_to_user_request', type_='foreignkey')
    op.drop_column('user_to_user_request', 'notification_id')
    op.drop_constraint(None, 'user_to_project_request', type_='foreignkey')
    op.drop_column('user_to_project_request', 'notification_id')
    op.drop_constraint(None, 'user_to_club_request', type_='foreignkey')
    op.drop_column('user_to_club_request', 'notification_id')
    op.drop_constraint(None, 'project_to_user_request', type_='foreignkey')
    op.drop_column('project_to_user_request', 'notification_id')
    op.drop_constraint(None, 'club_to_user_request', type_='foreignkey')
    op.drop_column('club_to_user_request', 'notification_id')
    # ### end Alembic commands ###
