"""empty message

Revision ID: 2583eb7b7d0a
Revises: 7bbd3c870ba0
Create Date: 2023-04-23 19:24:36.384468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2583eb7b7d0a'
down_revision = '7bbd3c870ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associates',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['user.id'], )
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('convos')
    op.drop_table('idea_viewers')
    op.drop_table('allies')
    op.drop_table('convo')
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('idea_group_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('idea_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('idea_profile_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'photo', ['photo_id'], ['id'])
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='cascade')
        batch_op.drop_column('profile_photo_id')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_convo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversation', ['convo_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_cover_photo_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_profile_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'photo', ['photo_id'], ['id'])
        batch_op.drop_column('profile_photo_id')
        batch_op.drop_column('cover_photo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_profile_photo_id_fkey', 'photo', ['profile_photo_id'], ['id'])
        batch_op.create_foreign_key('user_cover_photo_id_fkey', 'photo', ['cover_photo_id'], ['id'])
        batch_op.drop_column('photo_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_convo_id_fkey', 'convo', ['convo_id'], ['id'])

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('idea_profile_photo_id_fkey', 'photo', ['profile_photo_id'], ['id'])
        batch_op.create_foreign_key('idea_parent_id_fkey', 'idea', ['parent_id'], ['id'])
        batch_op.create_foreign_key('idea_group_id_fkey', 'group', ['group_id'], ['id'])
        batch_op.drop_column('photo_id')

    op.create_table('convo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('convo_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('activated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='convo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('allies',
    sa.Column('left_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user.id'], name='allies_left_id_fkey'),
    sa.ForeignKeyConstraint(['right_id'], ['user.id'], name='allies_right_id_fkey')
    )
    op.create_table('idea_viewers',
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name='idea_viewers_idea_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='idea_viewers_user_id_fkey', ondelete='CASCADE')
    )
    op.create_table('convos',
    sa.Column('convo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['convo_id'], ['convo.id'], name='convos_convo_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='convos_user_id_fkey')
    )
    op.drop_table('conversations')
    op.drop_table('associates')
    op.drop_table('conversation')
    # ### end Alembic commands ###
