"""empty message

Revision ID: 348cf15e26e9
Revises: 5c2e8f198944
Create Date: 2021-12-19 18:09:53.911240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348cf15e26e9'
down_revision = '5c2e8f198944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'club', ['id'])
    op.add_column('medium', sa.Column('club_channel_id', sa.Integer(), nullable=True))
    op.add_column('medium', sa.Column('project_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medium', 'club', ['club_channel_id'], ['id'])
    op.create_foreign_key(None, 'medium', 'project', ['project_channel_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'medium', type_='foreignkey')
    op.drop_constraint(None, 'medium', type_='foreignkey')
    op.drop_column('medium', 'project_channel_id')
    op.drop_column('medium', 'club_channel_id')
    op.drop_constraint(None, 'club', type_='unique')
    # ### end Alembic commands ###
