"""empty message

Revision ID: 43c5da63a4af
Revises: b8f2cf7a80df
Create Date: 2023-06-30 13:03:28.185021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c5da63a4af'
down_revision = 'b8f2cf7a80df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_clock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ownership_last_updated_at', sa.Integer(), nullable=True))

    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_timestamp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_timestamp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_clock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.drop_column('expiration_clock')
        batch_op.drop_column('expiration_timestamp')
        batch_op.drop_column('creation_timestamp')

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('ownership_last_updated_at')
        batch_op.drop_column('current_clock')

    # ### end Alembic commands ###
