"""empty message

Revision ID: 45655ab4b780
Revises: a5c244a0fb92
Create Date: 2022-08-21 14:30:01.218678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45655ab4b780'
down_revision = 'a5c244a0fb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medium', sa.Column('with_quote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medium', 'with_quote')
    # ### end Alembic commands ###
