"""empty message

Revision ID: 5139e0a07ed4
Revises: dbca12053e23
Create Date: 2024-01-30 23:25:40.752845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5139e0a07ed4'
down_revision = 'dbca12053e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.drop_constraint('permits_permit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('permits_wallet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'permit', ['permit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'wallet', ['wallet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('permits_wallet_id_fkey', 'wallet', ['wallet_id'], ['id'])
        batch_op.create_foreign_key('permits_permit_id_fkey', 'permit', ['permit_id'], ['id'])

    # ### end Alembic commands ###
