"""empty message

Revision ID: 54173bfc05d1
Revises: 090039c86e4a
Create Date: 2022-10-23 16:27:07.544417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54173bfc05d1'
down_revision = '090039c86e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium',
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('with_quote', sa.Boolean(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('quote_to_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['quote_to_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['medium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medium_creation_datetime'), 'medium', ['creation_datetime'], unique=False)
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('wall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['wall.id'], )
    )
    op.create_table('medium_downvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium_heart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inputs')
    op.drop_table('input_downvote')
    op.drop_index('ix_input_creation_datetime', table_name='input')
    op.drop_table('input')
    op.drop_table('input_heart')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('input_heart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['input.id'], name='input_heart_input_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], name='input_heart_voter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='input_heart_pkey')
    )
    op.create_table('input',
    sa.Column('creation_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('input_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('with_quote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reply_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quote_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='input_author_id_fkey'),
    sa.ForeignKeyConstraint(['channel_id'], ['idea.id'], name='input_channel_id_fkey'),
    sa.ForeignKeyConstraint(['quote_to_id'], ['input.id'], name='input_quote_to_id_fkey'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['input.id'], name='input_reply_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='input_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_input_creation_datetime', 'input', ['creation_datetime'], unique=False)
    op.create_table('input_downvote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['input.id'], name='input_downvote_input_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], name='input_downvote_voter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='input_downvote_pkey')
    )
    op.create_table('inputs',
    sa.Column('input_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wall_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['input.id'], name='inputs_input_id_fkey'),
    sa.ForeignKeyConstraint(['wall_id'], ['wall.id'], name='inputs_wall_id_fkey')
    )
    op.drop_table('medium_heart')
    op.drop_table('medium_downvote')
    op.drop_table('media')
    op.drop_index(op.f('ix_medium_creation_datetime'), table_name='medium')
    op.drop_table('medium')
    # ### end Alembic commands ###
