"""empty message

Revision ID: 56599ba2ec27
Revises: 6e09f906cd7c
Create Date: 2023-10-31 23:04:13.568316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56599ba2ec27'
down_revision = '6e09f906cd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decimals', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('decimals')

    # ### end Alembic commands ###
