"""file is-empty

Revision ID: 580ab7c6695f
Revises: f45bd3e84e5c
Create Date: 2024-08-04 18:04:03.800756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580ab7c6695f'
down_revision = 'f45bd3e84e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_empty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('is_empty')

    # ### end Alembic commands ###
