"""empty message

Revision ID: 61508164aaa1
Revises: 4ef10a151fc4
Create Date: 2021-02-11 19:25:51.942406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61508164aaa1'
down_revision = '4ef10a151fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
