"""empty message

Revision ID: 6744763254bd
Revises: 9a4ee0aa157a
Create Date: 2023-12-27 19:27:44.911301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6744763254bd'
down_revision = '9a4ee0aa157a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('erc360_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('block_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True),
    sa.Column('transaction_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True),
    sa.Column('log_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], name='action_erc360_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='action_pkey')
    )
    op.drop_table('event')
    # ### end Alembic commands ###
