"""empty message

Revision ID: 6b107e2ddd59
Revises: cd4bbef5f612
Create Date: 2021-08-01 19:02:28.355105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b107e2ddd59'
down_revision = 'cd4bbef5f612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'user', ['author_id'], ['id'])
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'author_id')
    # ### end Alembic commands ###
