"""empty message

Revision ID: 6e09f906cd7c
Revises: e4a4b388903c
Create Date: 2023-10-22 12:13:27.883130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e09f906cd7c'
down_revision = 'e4a4b388903c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    with op.batch_alter_table('token_amount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=78), nullable=True))
        batch_op.create_foreign_key(None, 'token', ['token_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('address')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_amount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=42), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('token_id')

    op.drop_table('token')
    # ### end Alembic commands ###
