"""empty message

Revision ID: 6f298c3375fc
Revises: 99e04e87f7cc
Create Date: 2021-01-20 16:12:24.442363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f298c3375fc'
down_revision = '99e04e87f7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creation_datetime', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_creation_datetime'), 'user', ['creation_datetime'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_creation_datetime'), table_name='user')
    op.drop_column('user', 'is_activated')
    op.drop_column('user', 'creation_datetime')
    # ### end Alembic commands ###
