"""empty message

Revision ID: 6f7cedfc034c
Revises: 1b866f353347
Create Date: 2021-04-27 19:56:41.935696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7cedfc034c'
down_revision = '1b866f353347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_club_to_user_request_type'), 'club_to_user_request', ['type'], unique=False)
    op.create_index(op.f('ix_project_to_user_request_type'), 'project_to_user_request', ['type'], unique=False)
    op.create_index(op.f('ix_user_to_club_request_type'), 'user_to_club_request', ['type'], unique=False)
    op.create_index(op.f('ix_user_to_project_request_type'), 'user_to_project_request', ['type'], unique=False)
    op.create_index(op.f('ix_user_to_user_request_type'), 'user_to_user_request', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_to_user_request_type'), table_name='user_to_user_request')
    op.drop_index(op.f('ix_user_to_project_request_type'), table_name='user_to_project_request')
    op.drop_index(op.f('ix_user_to_club_request_type'), table_name='user_to_club_request')
    op.drop_index(op.f('ix_project_to_user_request_type'), table_name='project_to_user_request')
    op.drop_index(op.f('ix_club_to_user_request_type'), table_name='club_to_user_request')
    # ### end Alembic commands ###
