"""empty message

Revision ID: 6fe2605382df
Revises: eb9c45a803b4
Create Date: 2023-10-03 18:37:26.310483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe2605382df'
down_revision = 'eb9c45a803b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_supply', sa.Integer(), nullable=True))
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_supply')

    # ### end Alembic commands ###
