"""events

Revision ID: 8dbeec0c9353
Revises: d8bea317ed51
Create Date: 2023-06-21 13:16:03.858481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbeec0c9353'
down_revision = 'd8bea317ed51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('block_hash', sa.String(length=64), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['idea.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_last_updated_at', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_key', ['id'])

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('timeline_last_updated_at')

    op.drop_table('event')
    # ### end Alembic commands ###
