"""empty message

Revision ID: 91153badcb7e
Revises: 54147b8c7812
Create Date: 2023-09-04 19:38:32.192080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91153badcb7e'
down_revision = '54147b8c7812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referendum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock', sa.BigInteger(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referendum', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('clock')

    # ### end Alembic commands ###
