"""empty message

Revision ID: 9a4ee0aa157a
Revises: 1f413c6b7c96
Create Date: 2023-12-07 23:59:00.787574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4ee0aa157a'
down_revision = '1f413c6b7c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dividend_token_amount', ['token_residual_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dividend_token_amount', ['token_amount_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dividend_claim', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dividend_token_amount', ['token_amount_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_claim', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
