"""empty message

Revision ID: a5c244a0fb92
Revises: 348cf15e26e9
Create Date: 2021-12-22 00:04:55.973837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c244a0fb92'
down_revision = '348cf15e26e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium_downvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medium', sa.Column('quote_to_id', sa.Integer(), nullable=True))
    op.add_column('medium', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.drop_constraint('medium_to_id_fkey', 'medium', type_='foreignkey')
    op.create_foreign_key(None, 'medium', 'medium', ['reply_to_id'], ['id'])
    op.create_foreign_key(None, 'medium', 'medium', ['quote_to_id'], ['id'])
    op.drop_column('medium', 'to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medium', sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medium', type_='foreignkey')
    op.drop_constraint(None, 'medium', type_='foreignkey')
    op.create_foreign_key('medium_to_id_fkey', 'medium', 'medium', ['to_id'], ['id'])
    op.drop_column('medium', 'reply_to_id')
    op.drop_column('medium', 'quote_to_id')
    op.drop_table('medium_downvote')
    # ### end Alembic commands ###
