"""empty message

Revision ID: ad3c0590b54e
Revises: febee7b587b3
Create Date: 2023-09-18 13:25:52.853612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad3c0590b54e'
down_revision = 'febee7b587b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holders',
    sa.Column('holder_id', sa.Integer(), nullable=True),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holder_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permit.id'], )
    )
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.drop_constraint('erc360_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('permit', schema=None) as batch_op:
        batch_op.drop_constraint('permit_wallet_id_fkey', type_='foreignkey')
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('spenders', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('priority')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_wallet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'wallet', ['main_wallet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_wallet_id')

    with op.batch_alter_table('spenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('permit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('permit_wallet_id_fkey', 'wallet', ['wallet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('erc360_group_id_fkey', 'group', ['group_id'], ['id'], ondelete='CASCADE')

    op.drop_table('holders')
    # ### end Alembic commands ###
