"""empty message

Revision ID: ad3ea1ed4166
Revises: 900e733c8e67
Create Date: 2021-04-26 16:48:37.502358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3ea1ed4166'
down_revision = '900e733c8e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'user', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'receiver_id')
    # ### end Alembic commands ###
