"""66 len

Revision ID: ad5f11990bf2
Revises: 8dbeec0c9353
Create Date: 2023-06-21 13:44:42.503182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5f11990bf2'
down_revision = '8dbeec0c9353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('block_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=66),
               existing_nullable=True)
        batch_op.alter_column('transaction_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=66),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('transaction_hash',
               existing_type=sa.String(length=66),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('block_hash',
               existing_type=sa.String(length=66),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
