"""empty message

Revision ID: b8e4d2b80681
Revises: 81c46034af99
Create Date: 2021-02-07 17:13:55.075272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e4d2b80681'
down_revision = '81c46034af99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
