"""shards

Revision ID: b8f2cf7a80df
Revises: ad5f11990bf2
Create Date: 2023-06-26 23:35:58.888724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f2cf7a80df'
down_revision = 'ad5f11990bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('identity', sa.LargeBinary(length=32), nullable=True),
    sa.Column('owner_address', sa.String(length=42), nullable=True),
    sa.Column('numerator', sa.Integer(), nullable=True),
    sa.Column('denominator', sa.Integer(), nullable=True),
    sa.Column('creation_clock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['idea.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shard')
    # ### end Alembic commands ###
