"""empty message

Revision ID: bd58b3d44078
Revises: f533eba3754f
Create Date: 2021-05-07 23:47:15.146382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd58b3d44078'
down_revision = 'f533eba3754f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('profile_photo_id', sa.Integer(), nullable=True))
    op.drop_constraint('club_profile_pic_id_fkey', 'club', type_='foreignkey')
    op.create_foreign_key(None, 'club', 'photo', ['profile_photo_id'], ['id'])
    op.drop_column('club', 'profile_pic_id')
    op.add_column('project', sa.Column('profile_photo_id', sa.Integer(), nullable=True))
    op.drop_constraint('project_profile_pic_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'photo', ['profile_photo_id'], ['id'])
    op.drop_column('project', 'profile_pic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('profile_pic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_profile_pic_id_fkey', 'project', 'photo', ['profile_pic_id'], ['id'])
    op.drop_column('project', 'profile_photo_id')
    op.add_column('club', sa.Column('profile_pic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.create_foreign_key('club_profile_pic_id_fkey', 'club', 'photo', ['profile_pic_id'], ['id'])
    op.drop_column('club', 'profile_photo_id')
    # ### end Alembic commands ###
