"""empty message

Revision ID: c2e609d10d20
Revises: 0168e7e195b0
Create Date: 2021-04-24 18:29:06.363758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e609d10d20'
down_revision = '0168e7e195b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('address', sa.String(), nullable=True))
    op.add_column('club', sa.Column('cos_rad_lat', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('club', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('rad_lng', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('show_location', sa.Boolean(), nullable=True))
    op.add_column('club', sa.Column('sin_rad_lat', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('address', sa.String(), nullable=True))
    op.add_column('project', sa.Column('cos_rad_lat', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('rad_lng', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('show_location', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('sin_rad_lat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'sin_rad_lat')
    op.drop_column('project', 'show_location')
    op.drop_column('project', 'rad_lng')
    op.drop_column('project', 'longitude')
    op.drop_column('project', 'latitude')
    op.drop_column('project', 'is_visible')
    op.drop_column('project', 'cos_rad_lat')
    op.drop_column('project', 'address')
    op.drop_column('club', 'sin_rad_lat')
    op.drop_column('club', 'show_location')
    op.drop_column('club', 'rad_lng')
    op.drop_column('club', 'longitude')
    op.drop_column('club', 'latitude')
    op.drop_column('club', 'is_visible')
    op.drop_column('club', 'cos_rad_lat')
    op.drop_column('club', 'address')
    # ### end Alembic commands ###
