"""empty message

Revision ID: c65eb8d477dc
Revises: cd0bf8d9ed7f
Create Date: 2021-02-20 18:24:34.897474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65eb8d477dc'
down_revision = 'cd0bf8d9ed7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_location', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_location')
    # ### end Alembic commands ###
