"""empty message

Revision ID: c7f375a2d603
Revises: 756dbf42f208
Create Date: 2023-09-07 23:57:13.214387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f375a2d603'
down_revision = '756dbf42f208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_ids_last_updated_at', sa.Integer(), nullable=True))
        batch_op.drop_column('shards_last_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shards_last_updated_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('token_ids_last_updated_at')

    # ### end Alembic commands ###
