"""empty message

Revision ID: d9de200dd82e
Revises: 6f7cedfc034c
Create Date: 2021-04-30 19:07:35.940808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9de200dd82e'
down_revision = '6f7cedfc034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubs')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='projects_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='projects_user_id_fkey')
    )
    op.create_table('clubs',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name='clubs_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='clubs_user_id_fkey')
    )
    # ### end Alembic commands ###
