"""empty message

Revision ID: dbca12053e23
Revises: 6744763254bd
Create Date: 2023-12-27 19:42:13.708590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbca12053e23'
down_revision = '6744763254bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_last_updated_at', sa.Integer(), nullable=True))
        batch_op.drop_column('events_last_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_last_updated_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('timeline_last_updated_at')

    # ### end Alembic commands ###
