"""empty message

Revision ID: e31c688b030f
Revises: 9b47db44a2ce
Create Date: 2021-09-15 18:37:04.563830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31c688b030f'
down_revision = '9b47db44a2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_to_user_request_sender_id_fkey', 'project_to_user_request', type_='foreignkey')
    op.create_foreign_key(None, 'project_to_user_request', 'project', ['sender_id'], ['id'], ondelete='CASCADE')
    op.add_column('role', sa.Column('permissionToAnswerInvite', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToChangePeopleRoles', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToCreateRoles', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToEditPage', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToPrivatePostCreator', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToPublicPostCreator', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToReceiveNotifications', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToRejectPeople', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissionToRejectPeople')
    op.drop_column('role', 'permissionToReceiveNotifications')
    op.drop_column('role', 'permissionToPublicPostCreator')
    op.drop_column('role', 'permissionToPrivatePostCreator')
    op.drop_column('role', 'permissionToEditPage')
    op.drop_column('role', 'permissionToCreateRoles')
    op.drop_column('role', 'permissionToChangePeopleRoles')
    op.drop_column('role', 'permissionToAnswerInvite')
    op.drop_constraint(None, 'project_to_user_request', type_='foreignkey')
    op.create_foreign_key('project_to_user_request_sender_id_fkey', 'project_to_user_request', 'club', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
