"""empty message

Revision ID: e4a4b388903c
Revises: 6e92e866fd9b
Create Date: 2023-10-22 11:27:48.033685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a4b388903c'
down_revision = '6e92e866fd9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_amount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=42), nullable=True))
        batch_op.drop_column('token_address')
        batch_op.drop_column('sender_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_amount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
