"""address => location_address

Revision ID: ebf3439e2589
Revises: 91153badcb7e
Create Date: 2023-09-07 17:37:48.111507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf3439e2589'
down_revision = '91153badcb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_claim', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'erc360_token_id', ['erc360_token_id_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_address', sa.String(), nullable=True))

    with op.batch_alter_table('referendum_vote', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'erc360_token_id', ['erc360_token_id_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_address', sa.String(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('location_address')

    with op.batch_alter_table('referendum_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.drop_column('location_address')

    with op.batch_alter_table('dividend_claim', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
