"""empty message

Revision ID: ed35b42d9ce8
Revises: 01da18e0ecf7
Create Date: 2021-03-20 12:06:02.343066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed35b42d9ce8'
down_revision = '01da18e0ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'notification', ['notification_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'notification_id')
    # ### end Alembic commands ###
