"""empty message

Revision ID: f45bd3e84e5c
Revises: 07357bab571b
Create Date: 2024-04-04 19:07:14.730773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45bd3e84e5c'
down_revision = '07357bab571b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referendums_last_updated_at', sa.Integer(), nullable=True))
        batch_op.drop_column('referendum_votes_last_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referendum_votes_last_updated_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('referendums_last_updated_at')

    # ### end Alembic commands ###
