"""empty message

Revision ID: f73b420a1591
Revises: e31c688b030f
Create Date: 2021-09-15 18:51:26.984106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73b420a1591'
down_revision = 'e31c688b030f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissionToCreatePrivatePosts', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissionToCreatePublicPosts', sa.Boolean(), nullable=True))
    op.drop_column('role', 'permissionToPrivatePostCreator')
    op.drop_column('role', 'permissionToPublicPostCreator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissionToPublicPostCreator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('permissionToPrivatePostCreator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('role', 'permissionToCreatePublicPosts')
    op.drop_column('role', 'permissionToCreatePrivatePosts')
    # ### end Alembic commands ###
