"""amounts

Revision ID: f9996003f19b
Revises: 5510552f1f41
Create Date: 2023-07-12 23:11:20.308974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9996003f19b'
down_revision = '5510552f1f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.drop_column('numerator')
        batch_op.drop_column('denominator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denominator', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numerator', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
