"""empty message

Revision ID: fd018e436a40
Revises: 
Create Date: 2024-04-04 15:31:42.609045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd018e436a40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sin_rad_lat', sa.Float(), nullable=True),
    sa.Column('cos_rad_lat', sa.Float(), nullable=True),
    sa.Column('rad_lng', sa.Float(), nullable=True),
    sa.Column('show_location', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erc360',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('current_clock', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Integer(), nullable=True),
    sa.Column('timeline_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('shards_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('bank_exchanges_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('dividend_claims_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('referendum_votes_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['file.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erc360_handle'), ['handle'], unique=True)

    op.create_table('token_amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sa.String(length=32), nullable=True),
    sa.Column('auth_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=160), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('main_wallet_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['main_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth_token'), ['auth_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_creation_datetime'), ['creation_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('associates',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['user.id'], )
    )
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clock', sa.BigInteger(), nullable=True),
    sa.Column('identifier', sa.Integer(), nullable=True),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('initial_token_amount_id', sa.Integer(), nullable=True),
    sa.Column('residual_token_amount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initial_token_amount_id'], ['token_amount.id'], ),
    sa.ForeignKeyConstraint(['residual_token_amount_id'], ['token_amount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erc360_shard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('creation_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('expiration_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('identifier', sa.BigInteger(), nullable=True),
    sa.Column('expiration_clock', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    op.create_table('permit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.LargeBinary(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['permit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referendum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Integer(), nullable=True),
    sa.Column('clock', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=True),
    sa.Column('viable_amount', sa.Integer(), nullable=True),
    sa.Column('cast_amount', sa.Integer(), nullable=True),
    sa.Column('in_favor_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_title'), ['title'], unique=False)

    op.create_table('spenders',
    sa.Column('spender_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], )
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permit_id'], ['permit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dividend_id', sa.Integer(), nullable=True),
    sa.Column('token_amount_id', sa.Integer(), nullable=True),
    sa.Column('erc360_shard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dividend_id'], ['dividend.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['erc360_shard_id'], ['erc360_shard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_amount_id'], ['token_amount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permits',
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permit.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], )
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referendum_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('sig', sa.LargeBinary(length=4), nullable=True),
    sa.Column('args', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['referendum_id'], ['referendum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_erc360_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('erc360_id', sa.Integer(), nullable=True),
    sa.Column('user_is_sender', sa.Boolean(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_id'], ['erc360.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_to_erc360_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_to_erc360_request_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_to_erc360_request_user_is_sender'), ['user_is_sender'], unique=False)

    op.create_table('user_to_user_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_to_user_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_to_user_request_type'), ['type'], unique=False)

    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referendum_id', sa.Integer(), nullable=True),
    sa.Column('erc360_shard_id', sa.Integer(), nullable=True),
    sa.Column('in_favor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['erc360_shard_id'], ['erc360_shard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referendum_id'], ['referendum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_token_amounts',
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('token_amount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['token_amount_id'], ['token_amount.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_token_amounts')
    op.drop_table('vote')
    with op.batch_alter_table('user_to_user_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_to_user_request_type'))

    op.drop_table('user_to_user_request')
    with op.batch_alter_table('user_to_erc360_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_to_erc360_request_user_is_sender'))
        batch_op.drop_index(batch_op.f('ix_user_to_erc360_request_type'))

    op.drop_table('user_to_erc360_request')
    op.drop_table('proposal')
    op.drop_table('permits')
    op.drop_table('dividend_claim')
    op.drop_table('bank')
    op.drop_table('spenders')
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_title'))

    op.drop_table('skill')
    op.drop_table('referendum')
    op.drop_table('permit')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))

    op.drop_table('notification')
    op.drop_table('followers')
    op.drop_table('event')
    op.drop_table('erc360_shard')
    op.drop_table('dividend')
    op.drop_table('associates')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_creation_datetime'))
        batch_op.drop_index(batch_op.f('ix_user_auth_token'))

    op.drop_table('user')
    op.drop_table('token_amount')
    with op.batch_alter_table('erc360', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erc360_handle'))

    op.drop_table('erc360')
    op.drop_table('wallet')
    op.drop_table('token')
    op.drop_table('location')
    op.drop_table('file')
    # ### end Alembic commands ###
