"""empty message

Revision ID: febee7b587b3
Revises: c7f375a2d603
Create Date: 2023-09-11 18:56:06.793418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'febee7b587b3'
down_revision = 'c7f375a2d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erc360_token_id', schema=None) as batch_op:
        batch_op.drop_column('identity')

    with op.batch_alter_table('spenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spenders', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('priority')

    with op.batch_alter_table('erc360_token_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
